import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./navbar"
import { Nav } from "react-day-picker";

const dmSans = DM_Sans(
  {
    subsets: ['latin']
  }
);

export const metadata: Metadata = {
  title: "vendorHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar />
      <body className={`${dmSans.className} antialiased font-size: 1rem`}>
        {children}
      </body>
    </html>
  );
}
